#!/bin/sh

set -e
echo "Running prerm script:" "$@"
#----------------------------------------------------

# Load environmental variables if exists.
[ -f /etc/default/hello ] && . /etc/default/hello

#----------------------------------------------------
exit 0
