name: Markdownlint
description: ""

inputs:
  skip-setup:
    description: "skip running actions/setup-node"
    required: false
    default: "false"
  args:
    description: "additional args for make markdownlint-run"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      if: ${{ inputs.skip-setup != 'true' }}
    - shell: bash
      run: make markdownlint-run ARGS="${{ inputs.args }}"
