name: Go Format
description: ""

inputs:
  # ---------------------------------------------------------
  # For setup-go.
  skip-setup-go:
    description: "skip actions/setup-go"
    required: false
    default: "false"
  go-version:
    description: "go-version for actions/setup-go"
    required: false
    default: "stable"
  go-version-file:
    description: "go-version-file for actions/setup-go"
    required: false
    default: ""
  check-latest:
    description: "check-latest for actions/setup-go"
    required: false
    default: "true"
  cache:
    description: "cache for actions/setup-go"
    required: false
    default: "false"
  cache-dependency-path:
    description: "cache-dependency-path for actions/setup-go"
    required: false
    default: ""
  # ---------------------------------------------------------
  args:
    description: "additional args for make go-fmt"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      if: ${{ inputs.skip-setup-go != 'true' }}
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        check-latest: ${{ inputs.check-latest }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - shell: bash
      run: make go-fmt ARGS="${{ inputs.args }}"
